language: c
before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
- sleep 3
- export DISPLAY=:1.0
- wget http://downloads.arduino.cc/arduino-1.6.13-linux64.tar.xz
- tar xf arduino-1.6.13-linux64.tar.xz
- rm -rf arduino-1.6.13/libraries/LiquidCrystal
- cp -Rf ArduinoAddons/Arduino_1.6.x/* arduino-1.6.13/
- wget -c "https://raw.githubusercontent.com/arduino/Arduino/master/hardware/arduino/avr/bootloaders/stk500v2/stk500boot_v2_mega2560.hex"
- cp stk500boot_v2_mega2560.hex arduino-1.6.13/hardware/arduino/avr/bootloaders/stk500v2/
- cp stk500boot_v2_mega2560.hex arduino-1.6.13/hardware/marlin/avr/bootloaders/
- find arduino-1.6.13/ -name platform.local.txt -delete
script:
- mkdir release
- VARIANTS=$(ls Firmware/variants/)
- touch Firmware/Configuration_prusa.h
- for VARIANT in $VARIANTS; do rm Firmware/Configuration_prusa.h ; cp Firmware/variants/${VARIANT}
  Firmware/Configuration_prusa.h ; Scripts/haribo_config.sh ; arduino-1.6.13/arduino
  --pref build.path=. --verify --verbose-build --board marlin:avr:rambo $PWD/Firmware/Firmware.ino
  ; mv Firmware.ino.hex release/Haribo_3030_Edition-"${VARIANT}"ex ; Scripts/reprap_lcd_config.sh
  ; arduino-1.6.13/arduino --pref build.path=. --verify --verbose-build --board marlin:avr:rambo
  $PWD/Firmware/Firmware.ino ; mv Firmware.ino.hex release/Haribo_3030_Edition-reprap-lcd-"${VARIANT}"ex
  ; done
deploy:
  provider: releases
  api_key:
  - secure: dev05JO/wYPX1biq+QvHll6Gs4C8/hQEdGhhUJjXkbuugmwXCeL7wSWxDhNFbZdA7JJdLFPcDwY1tcdiykg7dzoNrIaWC2Hi2LkWeZ+OLkO/5rP1Y0GrliTJzemkdq5YfRfe+tq1Uch/SRG4UGY5Hkn9OKs+xFVhJ/lq1KnjU1UiuH6pC4UQfj8CFAxT3rlh5FTGs819O1dGQXRXl+facSZDUFK/6QCnSAu3NfogTS0D5dQc73J+5GHKUOTAxBMymaPmV94Qj7u6vu+8Bvqx6p0y3l84Vbb9P2Op+R6rJlx25bxNs/xKwP2OUNmr82mwQOVNPsgWqjwLHVMSflkgm2gLJhLKiXdEnrdN23vlCyB23VZw3lc6OBiXraCBBQvD/SKp5jSaKsLbsIx+U+4BOLKAfvIxiz5lpAG2eIZ5EVeZpaeZOm87llFrfPxffJLshZtJRZdzhALx1dV9M0otNMrXncumcPinVYMJAwe9hnh32iYqfbLx216MRbdI2Mf74TdCKOkWGQcWpSK7PW2iVHcWpz5I+RzmVevmUSgFOEIo59jBGDzL0M52z+/pQwurdq/YqRmg7u11od/GQ2ty3evpApfGoqV2O+PuvqMqFUAwi6vSvaVVDllcl3zvaLmlPK5AJtUnGOLYiVutVKVvYhqGOrhunH4H5z09KOoLVRI=
  skip_cleanup: true
  file_glob: true
  file: release/*
  on:
    branch: MK2-DEPLOY
